name: rhub-ci.yaml

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: r-hub/actions/checkout@main
    - uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: rhub.yaml
        inputs: '{ "config": "clang-asan,clang-ubsan,rchk,valgrind" }'
