# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: test-coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          Ncpus: 4

      - name: Install Python packages for testing
        run: |
          dir.create("~/.pip", showWarnings = FALSE, recursive = TRUE)
          writeLines(
            c("[global]", "break-system-packages = true", "user = true"),
            "~/.pip/pip.conf"
          )
          if (Sys.which("pip3") != "") {
            system("pip3 install pyarrow pandas polars")
          } else {
            system("pip install pyarrow pandas polars")
          }
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: gaborcsardi/uncovr
          needs: coverage

      - name: Test coverage
        run: |
          uncovr::test()
          uncovr::lcov(output = "lcov.info")
        shell: Rscript {0}

      - uses: codecov/codecov-action@v5
        with:
          # Fail if error if not on PR, or if on PR and token is given
          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          plugins: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
